### ISSUE TITLE
Allow naming of threads in makeCluster()

### ISSUE THREAD

**Issue by jmb01** [OHDSI/ParallelLogger#13]
This would be helpful for tracking.

**Comment by schuemie** [comment]
I'm not sure I understand. Could you provide a use case?

**Comment by schuemie** [comment]
I'd like to distinguish two concepts in ParallelLogger:

1. A **thread** is a node in the cluster that can perform jobs. It is in fact a separate R instance. 
2. A **job** is a bit of work that threads can perform. It is a combination of a function call (e.g. `getAvgDelay ()` in your example) with the arguments for that function call (e.g. 'JFK').

A thread will typically handle multiple jobs. For example , the list of flights in your example may be 100 long, and these could be distributed over 4 threads, so each thread would perform 25 jobs on average. So I'm not following why a thread could be named after a job, unless you'd want to rename the thread with every job. 

One pattern I sometimes use is, at the start of a job, I log some part of the argument for that job. Then, if something happens during that job, I can link the message in that thread to the earlier message about the argument. The log would for example look like this:
```
[Thread 1]  TRACE  Starting job JFK
[Thread 2]  TRACE  Starting job EWR
[Thread 1]  FATAL  Something bad happened
```
I would then know the bad thing happened while processing the job with input 'JFK'.

**Comment by jmb01** [comment]
Thanks @schuemie. 

The approach you mention is the one I am currently using in my work, but with long log files I was getting tired of scrolling to the top of the file to match thread numbers with job names. 

However, I understand why you might not want to name a thread after a job, so I'll close this issue and in the future just put the job name at the beginning of all my logging calls.
