### ISSUE TITLE
ParallelLogger::saveSettingsToJson drops names when saving named vectors

### ISSUE THREAD

**Issue by jreps** [OHDSI/ParallelLogger#18]
see https://github.com/OHDSI/PatientLevelPrediction/issues/305

reproducible example:

test <- c(1:10)
names(test) <- paste0('name_', 1:10)
ParallelLogger::saveSettingsToJson(test, file.path(getwd(), 'exampleJson.json'))

check the json and you will see there are no names

**Comment by schuemie** [comment]
I think I agree with [this post](https://github.com/jeroen/jsonlite/issues/76#issuecomment-82635906), arguing we shouldn't want to support named vectors. Instead, couldn't you use a data frame or list?
