### ISSUE TITLE
loadSettingsFromJson doesn't restore original object from json if it's a list with a df as first element.

### ISSUE THREAD

**Issue by egillax** [OHDSI/ParallelLogger#19]
Reproducible example:

```R
fileName <- tempfile()
  settings <- list(
    b = data.frame(
      x = c(1, 2, 3),
      y = c("p", "q", "r"),
      stringsAsFactors = FALSE
    ),
    a = "a"
  )
  saveSettingsToJson(settings, fileName)
  settings2 <- loadSettingsFromJson(fileName)
```
settings2 is not the same as settings.

If I comment out the function ```restoreDataFrames`` this load correctly, and all the tests pass. I currently just work around this by setting the df as the last element instead of first.

**Comment by jreps** [comment]
this issue is also causing attributes to be dropped when saving a list with only a data.frame

**Comment by schuemie** [comment]
Thanks. Should be fixed in the develop branch now
