### ISSUE TITLE
Corrupted log file

### ISSUE THREAD

**Issue by ganisimov** [OHDSI/ParallelLogger#23]
Sometimes log file contains lines like these:
```
...
2023-08-15 06:54:28	[Thread 2]	TRACE			Thread 2 terminated
opping cluster
2023-08-15 06:54:28	[Thread 1]	TRACE			Thread 1 terminated
...
```
Notice second line which doesn't contain expected fields and "Stopping cluster" record is trimmed.

This causes error when parsing log file using read.table:
```
logs <- utils::read.table(
    file = logFilePath,
    header = FALSE,
    sep = "\t",
    stringsAsFactors = FALSE
)
Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  : 
  line 1227 did not have 6 elements
```

We're facing this when running `Achilles::achilles()` on Windows from within script using Rscript.exe. Achilles internally uses read.table so it's affected by the trimmed line. It doesn't happen all the time, but something like 3 of 5 runs. When running the same code directly from terminal, i.e. running R.exe, the problem doesn't seem to appear.

It looks like a fix for this could be simply putting line which logs "Stopping cluster" before line which actually stops a cluster, like here:
https://github.com/OHDSI/ParallelLogger/compare/develop...ganisimov:ParallelLogger:develop
At least with that change the issue wasn't reproduced through several runs.

To reproduce the issue adjust arguments and connectionDetails vars according to your environment in the code below, save it as file, say repro.R, and run with Rscript.exe, e.g. `rscript.exe "repro.R"`.
```
arguments <- list(
    cdmDatabaseSchema = "cdm",
    resultsDatabaseSchema = "resuts",
    sourceName = "MyCdmSource",
    numAchillesThreads = 2,
    outputFolder = "AchillesTest"
)
connectionDetails <- DatabaseConnector::createConnectionDetails(
    dbms = "redshift",
    user = "myusername",
    password = "mysecretpassword",
    server = "myserver.abcdefg.us-east-1.redshift.amazonaws.com/mydatabase",
    port = 5439,
    extraSettings = "ssl=true&sslfactory=com.amazon.redshift.ssl.NonValidatingFactory"
)
setwd("c:/temp")
analysisDetails <- Achilles::getAnalysisDetails()
analysisIds <- analysisDetails$ANALYSIS_ID[-which(analysisDetails$IS_DEFAULT==0)]
Achilles::achilles(
    connectionDetails = connectionDetails,
    cdmDatabaseSchema = arguments$cdmDatabaseSchema,
    resultsDatabaseSchema = arguments$resultsDatabaseSchema,
    scratchDatabaseSchema = arguments$resultsDatabaseSchema,
    vocabDatabaseSchema = arguments$cdmDatabaseSchema,
    sourceName = gsub(pattern = "'", replacement = "", x = arguments$sourceName),
    analysisIds = analysisIds,
    createTable = TRUE,
    smallCellCount = 0,
    cdmVersion = "5.4",
    createIndices = FALSE,
    numThreads = as.integer(arguments$numAchillesThreads),
    dropScratchTables = TRUE,
    outputFolder = arguments$outputFolder
)
logFilePath <- file.path(arguments$outputFolder, "log_achilles.txt")
logs <- utils::read.table(
    file = logFilePath,
    header = FALSE,
    sep = "\t",
    stringsAsFactors = FALSE
)
```

R.version
```
platform       x86_64-w64-mingw32
arch           x86_64
os             mingw32
system         x86_64, mingw32
status
major          4
minor          1.0
year           2021
month          05
day            18
svn rev        80317
language       R
version.string R version 4.1.0 (2021-05-18)
nickname       Camp Pontanezen
```

**Comment by ganisimov** [comment]
This seems to be the same issue - https://github.com/OHDSI/Achilles/issues/732

**Comment by schuemie** [comment]
I've added the change you requested, but in general there is no guarantee that the log file is completely uncorrupted. The different threads all write to the same file, and there's no synchronization. Most of the times this works fine, because writes are fast, but sometimes different thread write at *exactly* the same time. For human review of the log files this should be fine. If you're automatically processing the log file, I recommend making it robust to these issues, for example dropping ill-formatted lines.

**Comment by ganisimov** [comment]
OK, got it. Thank you!
