### ISSUE TITLE
makeCluster fail on windows 7

### ISSUE THREAD

**Issue by sravel** [OHDSI/ParallelLogger#3]
Hello, thank you for your package, it fits perfectly with what I look for. However, I have a problem I can not seem to use the "cluster <- makeCluster (numberOfThreads = 3)" on windows 7. I have tested on Windows 10 and it's good.
Does the function works with Windows 7?

Thanks in advance

**Comment by schuemie** [comment]
Yes, I've been using it on Windows 7 for a while. What's the error message? What version of R are you running?

**Comment by sravel** [comment]
I use version 3.5.0, but I had some warning of libraries build in another version.
I deleted everything and reinstalled in version 3.6.1 and it's ok.
sorry for disturbing
