### ISSUE TITLE
Conflict with latest ggplot

### ISSUE THREAD

**Issue by hms1** [OHDSI/ParallelLogger#5]
This issue came to light when running  diagnostics failed in PLE.

Updating to the latest version of ggplot2 (3.3.0) causes ggplot to error following the initiation of ParallelLogger, but only when the plot data contains missing values. 

Before initiating ParallelLogger, everything works fine:

```R
test_geom_point_missing_data <- function(){
  ggplot2::ggplot(tidyr::tibble(x = c(0,1,3), y = c(NA,2,3))) + 
    ggplot2::geom_point(ggplot2::aes(x = x, y = y))
}

devtools::install_version("ggplot2", version = "3.3.0", repos = "http://cran.us.r-project.org")

test_geom_point_missing_data()
```
After initiating ParallelLogger, there is an error:
```R
ParallelLogger::addDefaultFileLogger(file.path("log.txt"))

test_geom_point_missing_data()
```
```
Error in sys.call(-i)[[1]] == ".signalSimpleWarning" : 
  comparison (1) is possible only for atomic and list types
```

Using ggplot2 version 3.2.0, there is no error (restart R first):
```R
test_geom_point_missing_data <- function(){
  ggplot2::ggplot(tidyr::tibble(x = c(0,1,3), y = c(NA,2,3))) + 
    ggplot2::geom_point(ggplot2::aes(x = x, y = y))
}

devtools::install_version("ggplot2", version = "3.2.0", repos = "http://cran.us.r-project.org")

ParallelLogger::addDefaultFileLogger(file.path("log.txt"))

test_geom_point_missing_data()
```
As far as I can tell, the issues arises when ggplot warns that NA values have been dropped, hence the interaction with ParallelLogger.

```
Warning message:
Removed 1 rows containing missing values (geom_point). 
```

Adding na.rm=T to geom_point also solves the issue using ggplot2 v3.3.0, as this option suppresses the warning message.

**Comment by schuemie** [comment]
Thanks for a very clear issue report!

I just pushed a fix to the develop branch. You can install from there if you need it right now:

```r
devtools::install_github("ohdsi/ParallelLogger", ref = "develop")
```

It will be included in a future release.

**Comment by hms1** [comment]
Many thanks :)
