### ISSUE TITLE
Progress indicator

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/ParallelLogger#8]
In verbose mode it would be nice to know how many check are still pending. For exampe say:

Processing check description: measurePersonCompleteness **(1/x)**

**Comment by fdefalco** [comment]
Question is if ParallelLogger offers any output to indicate progress when running single threaded?

**Comment by schuemie** [comment]
Currently not, for two reasons:
1. For single threaded execution it relies on `lapply()`, which does not support progress bars.
2. In single-threaded mode the output of the thread reaches the console (whereas in multi-threading it does not). This would often look ugly if combined with a progress bar.

(1) could be easily solved by using `plyr::llply()` with `.progress = "text"`. (2) suggests by default the progress bar is off when single-threaded?
