### ISSUE TITLE
ParallelLogger may not be capturing events reported by DatabaseConnector while inserting

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/ParallelLogger#9]
Observed: Warnings from DatabaseConnector while uploading/inserting data was not seen in file logger (event = TRACE).
Expected: Warnings form DatabaseConnector should be in logger

Probable explanation - the warnings were from database system or Java, and somehow ParallelLogger does not see it?

**Comment by schuemie** [comment]
Ideally these Java errors (warnings?) should be recast as R error (warnings) to ParallelLogger can log them.

**Comment by schuemie** [comment]
Closing this issue here. Please open an issue for DatabaseConnector, listing the exact warnings you're observing (and how to reproduce them)
